#!/bin/bash

# check for root rights
if [ `whoami` != root ]; then
echo This script needs root permissions
exit 5
fi

# setup polyvr app and launcher
dir=$(pwd)
su $SUDO_USER -c "./extras/utils/createIcon $dir"
cp $dir/PolyVR.desktop /usr/share/applications/PolyVR.desktop
cp $dir/application-x-polyvr.xml /usr/share/mime/packages/application-x-polyvr.xml
cp $dir/ressources/gui/logo_icon.png /usr/share/icons/hicolor/scalable/mimetypes/application-x-polyvr.png
update-mime-database /usr/share/mime
update-desktop-database
update-icon-caches /usr/share/icons/*


sudo apt-get update
sudo apt-get upgrade
sudo apt-get install -y git codeblocks codeblocks-contrib

if [ ! -e dependencies ]; then
  git clone https://github.com/Victor-Haefner/polyvr-depends.git dependencies
fi

cd dependencies
git pull
sudo ./install dev
