#!/bin/bash

sudo add-apt-repository -y ppa:damien-moore/codeblocks-stable
#sudo add-apt-repository -y ppa:thomas-schiex/blender
sudo apt-get update
sudo apt-get install -y git codeblocks codeblocks-contrib

if [ ! -e dependencies ]; then
  git clone https://github.com/Victor-Haefner/polyvr-depends.git dependencies
fi

cd dependencies
git pull
sudo ./install dev
