#!/bin/bash

# get script directory
SOURCE="${BASH_SOURCE[0]}"
DIR="$( dirname "$SOURCE" )"
while [ -h "$SOURCE" ]
do 
  SOURCE="$(readlink "$SOURCE")"
  [[ $SOURCE != /* ]] && SOURCE="$DIR/$SOURCE"
  DIR="$( cd -P "$( dirname "$SOURCE"  )" && pwd )"
done
DIR="$( cd -P "$( dirname "$SOURCE" )" && pwd )"
cd $DIR

if [ ! -e build ]; then
	mkdir build
fi

cd build
rm -rf *
cmake -G "Visual Studio 15 2017 Win64" ..
cmake --build . --config Release
cd $DIR

cp build/Release/VRServer.exe VRServer
