#!/bin/bash
libs="OSGBase:OSGContribCSMSimplePlugin:OSGContribWebInterface:OSGGroup:OSGUtil:OSGCluster:OSGContribCSM:OSGDrawable:OSGImageFileIO:OSGWindowGLUT:OSGContribBackgroundLoader:OSGContribGUI:OSGDynamics:OSGState:OSGWindow:OSGContribCgFX:OSGContribPLY:OSGEffectGroups:OSGSystem:OSGWindowX:OSGContribComputeBase:OSGContribTrapezoidalShadowMaps:OSGFileIO:OSGText"
export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/usr/lib/opensg && export OSG_LOAD_LIBS=$libs && ./VRServer -m -w $1 -geometry 512x512+0+0
