/*
 * Autogenerated by the Meson build system.
 * Do not edit, your changes will be lost.
 */

#pragma once

#define DATADIR "/usr/local/share"

#define GETTEXT_PACKAGE "gtksourceview-4"

#define GSV_API_VERSION "4"

#define _GTK_SOURCE_EXTERN __attribute__((visibility("default"))) extern

