/*---------------------------------------------------------------------------*\
 *                                OpenSG                                     *
 *                                                                           *
 *                                                                           *
 *               Copyright (C) 2000-2013 by the OpenSG Forum                 *
 *                                                                           *
 *                            www.opensg.org                                 *
 *                                                                           *
 * contact: dirk@opensg.org, gerrit.voss@vossg.org, carsten_neumann@gmx.net  *
 *                                                                           *
\*---------------------------------------------------------------------------*/
/*---------------------------------------------------------------------------*\
 *                                License                                    *
 *                                                                           *
 * This library is free software; you can redistribute it and/or modify it   *
 * under the terms of the GNU Library General Public License as published    *
 * by the Free Software Foundation, version 2.                               *
 *                                                                           *
 * This library is distributed in the hope that it will be useful, but       *
 * WITHOUT ANY WARRANTY; without even the implied warranty of                *
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU         *
 * Library General Public License for more details.                          *
 *                                                                           *
 * You should have received a copy of the GNU Library General Public         *
 * License along with this library; if not, write to the Free Software       *
 * Foundation, Inc., 675 Mass Ave, Cambridge, MA 02139, USA.                 *
 *                                                                           *
\*---------------------------------------------------------------------------*/
/*---------------------------------------------------------------------------*\
 *                                Changes                                    *
 *                                                                           *
 *                                                                           *
 *                                                                           *
 *                                                                           *
 *                                                                           *
 *                                                                           *
\*---------------------------------------------------------------------------*/

/*****************************************************************************\
 *****************************************************************************
 **                                                                         **
 **                  This file is automatically generated.                  **
 **                                                                         **
 **          Any changes made to this file WILL be lost when it is          **
 **           regenerated, which can become necessary at any time.          **
 **                                                                         **
 **     Do not change this file, changes should be done in the derived      **
 **     class VRShadowEngine!
 **                                                                         **
 *****************************************************************************
\*****************************************************************************/

#include <cstdlib>
#include <cstdio>

#include <OpenSG/OSGConfig.h>




#include "VRShadowEngineBase.h"
#include "VRShadowEngine.h"

#include <boost/bind.hpp>

#ifdef WIN32 // turn off 'this' : used in base member initializer list warning
#pragma warning(disable:4355)
#endif

OSG_BEGIN_NAMESPACE

/***************************************************************************\
 *                            Description                                  *
\***************************************************************************/

/*! \class OSG::VRShadowEngine

 */

/***************************************************************************\
 *                        Field Documentation                              *
\***************************************************************************/

/*! \var Color4f         VRShadowEngineBase::_sfShadowColor

*/

/*! \var Int32           VRShadowEngineBase::_sfForceTextureUnit

*/


/***************************************************************************\
 *                      FieldType/FieldTrait Instantiation                 *
\***************************************************************************/

#if !defined(OSG_DO_DOC) || defined(OSG_DOC_DEV)
PointerType FieldTraits<VRShadowEngine *, nsOSG>::_type(
    "VRShadowEnginePtr",
    "ShadowMapEnginePtr",
    VRShadowEngine::getClassType(),
    nsOSG);
#endif

OSG_FIELDTRAITS_GETTYPE_NS(VRShadowEngine *, nsOSG)

OSG_EXPORT_PTR_SFIELD_FULL(PointerSField,
                           VRShadowEngine *,
                           nsOSG);

OSG_EXPORT_PTR_MFIELD_FULL(PointerMField,
                           VRShadowEngine *,
                           nsOSG);

/***************************************************************************\
 *                         Field Description                               *
\***************************************************************************/

void VRShadowEngineBase::classDescInserter(TypeObject &oType)
{
    FieldDescriptionBase *pDesc = NULL;


    pDesc = new SFColor4f::Description(
        SFColor4f::getClassType(),
        "shadowColor",
        "",
        ShadowColorFieldId, ShadowColorFieldMask,
        false,
        (Field::SFDefaultFlags | Field::FStdAccess),
        static_cast<FieldEditMethodSig>(&VRShadowEngine::editHandleShadowColor),
        static_cast<FieldGetMethodSig >(&VRShadowEngine::getHandleShadowColor));

    oType.addInitialDesc(pDesc);

    pDesc = new SFInt32::Description(
        SFInt32::getClassType(),
        "forceTextureUnit",
        "",
        ForceTextureUnitFieldId, ForceTextureUnitFieldMask,
        false,
        (Field::SFDefaultFlags | Field::FStdAccess),
        static_cast<FieldEditMethodSig>(&VRShadowEngine::editHandleForceTextureUnit),
        static_cast<FieldGetMethodSig >(&VRShadowEngine::getHandleForceTextureUnit));

    oType.addInitialDesc(pDesc);
}


VRShadowEngineBase::TypeObject VRShadowEngineBase::_type(
    VRShadowEngineBase::getClassname(),
    Inherited::getClassname(),
    "NULL",
    nsOSG, //Namespace
    reinterpret_cast<PrototypeCreateF>(&VRShadowEngineBase::createEmptyLocal),
    VRShadowEngine::initMethod,
    VRShadowEngine::exitMethod,
    reinterpret_cast<InitalInsertDescFunc>(&VRShadowEngine::classDescInserter),
    false,
    0,
    "<?xml version=\"1.0\" ?>\n"
    "\n"
    "<FieldContainer\n"
    "   name=\"VRShadowEngine\"\n"
    "   parent=\"ShadowMapEngine\"\n"
    "   library=\"Group\"\n"
    "   structure=\"concrete\"\n"
    "   pointerfieldtypes=\"both\"\n"
    "   systemcomponent=\"true\"\n"
    "   parentsystemcomponent=\"true\"\n"
    "   isNodeCore=\"false\"\n"
    "   docGroupBase=\"GrpGroupLightShadowEngines\"\n"
    "   >\n"
    "  <Field\n"
    "     name=\"shadowColor\"\n"
    "     category=\"data\"\n"
    "     type=\"Color4f\"\n"
    "     cardinality=\"single\"\n"
    "     visibility=\"external\"\n"
    "     defaultValue=\"0.f, 0.f, 0.f, 1.f\"\n"
    "     access=\"public\"\n"
    "     >\n"
    "  </Field>\n"
    "  <Field\n"
    "     name=\"forceTextureUnit\"\n"
    "     type=\"Int32\"\n"
    "     cardinality=\"single\"\n"
    "     visibility=\"external\"\n"
    "     defaultValue=\"-1\"\n"
    "     access=\"public\"\n"
    "     >\n"
    "  </Field>\n"
    "</FieldContainer>\n",
    ""
    );

/*------------------------------ get -----------------------------------*/

FieldContainerType &VRShadowEngineBase::getType(void)
{
    return _type;
}

const FieldContainerType &VRShadowEngineBase::getType(void) const
{
    return _type;
}

UInt32 VRShadowEngineBase::getContainerSize(void) const
{
    return sizeof(VRShadowEngine);
}

/*------------------------- decorator get ------------------------------*/


SFColor4f *VRShadowEngineBase::editSFShadowColor(void)
{
    editSField(ShadowColorFieldMask);

    return &_sfShadowColor;
}

const SFColor4f *VRShadowEngineBase::getSFShadowColor(void) const
{
    return &_sfShadowColor;
}


SFInt32 *VRShadowEngineBase::editSFForceTextureUnit(void)
{
    editSField(ForceTextureUnitFieldMask);

    return &_sfForceTextureUnit;
}

const SFInt32 *VRShadowEngineBase::getSFForceTextureUnit(void) const
{
    return &_sfForceTextureUnit;
}






/*------------------------------ access -----------------------------------*/

SizeT VRShadowEngineBase::getBinSize(ConstFieldMaskArg whichField)
{
    SizeT returnValue = Inherited::getBinSize(whichField);

    if(FieldBits::NoField != (ShadowColorFieldMask & whichField))
    {
        returnValue += _sfShadowColor.getBinSize();
    }
    if(FieldBits::NoField != (ForceTextureUnitFieldMask & whichField))
    {
        returnValue += _sfForceTextureUnit.getBinSize();
    }

    return returnValue;
}

void VRShadowEngineBase::copyToBin(BinaryDataHandler &pMem,
                                  ConstFieldMaskArg  whichField)
{
    Inherited::copyToBin(pMem, whichField);

    if(FieldBits::NoField != (ShadowColorFieldMask & whichField))
    {
        _sfShadowColor.copyToBin(pMem);
    }
    if(FieldBits::NoField != (ForceTextureUnitFieldMask & whichField))
    {
        _sfForceTextureUnit.copyToBin(pMem);
    }
}

void VRShadowEngineBase::copyFromBin(BinaryDataHandler &pMem,
                                    ConstFieldMaskArg  whichField)
{
    Inherited::copyFromBin(pMem, whichField);

    if(FieldBits::NoField != (ShadowColorFieldMask & whichField))
    {
        editSField(ShadowColorFieldMask);
        _sfShadowColor.copyFromBin(pMem);
    }
    if(FieldBits::NoField != (ForceTextureUnitFieldMask & whichField))
    {
        editSField(ForceTextureUnitFieldMask);
        _sfForceTextureUnit.copyFromBin(pMem);
    }
}

//! create a new instance of the class
VRShadowEngineTransitPtr VRShadowEngineBase::createLocal(BitVector bFlags)
{
    VRShadowEngineTransitPtr fc;

    if(getClassType().getPrototype() != NULL)
    {
        FieldContainerTransitPtr tmpPtr =
            getClassType().getPrototype()-> shallowCopyLocal(bFlags);

        fc = dynamic_pointer_cast<VRShadowEngine>(tmpPtr);
    }

    return fc;
}

//! create a new instance of the class, copy the container flags
VRShadowEngineTransitPtr VRShadowEngineBase::createDependent(BitVector bFlags)
{
    VRShadowEngineTransitPtr fc;

    if(getClassType().getPrototype() != NULL)
    {
        FieldContainerTransitPtr tmpPtr =
            getClassType().getPrototype()-> shallowCopyDependent(bFlags);

        fc = dynamic_pointer_cast<VRShadowEngine>(tmpPtr);
    }

    return fc;
}

//! create a new instance of the class
VRShadowEngineTransitPtr VRShadowEngineBase::create(void)
{
    VRShadowEngineTransitPtr fc;

    if(getClassType().getPrototype() != NULL)
    {
        FieldContainerTransitPtr tmpPtr =
            getClassType().getPrototype()-> shallowCopy();

        fc = dynamic_pointer_cast<VRShadowEngine>(tmpPtr);
    }

    return fc;
}

VRShadowEngine *VRShadowEngineBase::createEmptyLocal(BitVector bFlags)
{
    VRShadowEngine *returnValue;

    newPtr<VRShadowEngine>(returnValue, bFlags);

    returnValue->_pFieldFlags->_bNamespaceMask &= ~bFlags;

    return returnValue;
}

//! create an empty new instance of the class, do not copy the prototype
VRShadowEngine *VRShadowEngineBase::createEmpty(void)
{
    VRShadowEngine *returnValue;

    newPtr<VRShadowEngine>(returnValue, Thread::getCurrentLocalFlags());

    returnValue->_pFieldFlags->_bNamespaceMask &=
        ~Thread::getCurrentLocalFlags();

    return returnValue;
}


FieldContainerTransitPtr VRShadowEngineBase::shallowCopyLocal(
    BitVector bFlags) const
{
    VRShadowEngine *tmpPtr;

    newPtr(tmpPtr, dynamic_cast<const VRShadowEngine *>(this), bFlags);

    FieldContainerTransitPtr returnValue(tmpPtr);

    tmpPtr->_pFieldFlags->_bNamespaceMask &= ~bFlags;

    return returnValue;
}

FieldContainerTransitPtr VRShadowEngineBase::shallowCopyDependent(
    BitVector bFlags) const
{
    VRShadowEngine *tmpPtr;

    newPtr(tmpPtr, dynamic_cast<const VRShadowEngine *>(this), ~bFlags);

    FieldContainerTransitPtr returnValue(tmpPtr);

    tmpPtr->_pFieldFlags->_bNamespaceMask = bFlags;

    return returnValue;
}

FieldContainerTransitPtr VRShadowEngineBase::shallowCopy(void) const
{
    VRShadowEngine *tmpPtr;

    newPtr(tmpPtr,
           dynamic_cast<const VRShadowEngine *>(this),
           Thread::getCurrentLocalFlags());

    tmpPtr->_pFieldFlags->_bNamespaceMask &= ~Thread::getCurrentLocalFlags();

    FieldContainerTransitPtr returnValue(tmpPtr);

    return returnValue;
}




/*------------------------- constructors ----------------------------------*/

VRShadowEngineBase::VRShadowEngineBase(void) :
    Inherited(),
    _sfShadowColor            (Color4f(0.f, 0.f, 0.f, 1.f)),
    _sfForceTextureUnit       (Int32(-1))
{
}

VRShadowEngineBase::VRShadowEngineBase(const VRShadowEngineBase &source) :
    Inherited(source),
    _sfShadowColor            (source._sfShadowColor            ),
    _sfForceTextureUnit       (source._sfForceTextureUnit       )
{
}


/*-------------------------- destructors ----------------------------------*/

VRShadowEngineBase::~VRShadowEngineBase(void)
{
}


GetFieldHandlePtr VRShadowEngineBase::getHandleShadowColor     (void) const
{
    SFColor4f::GetHandlePtr returnValue(
        new  SFColor4f::GetHandle(
             &_sfShadowColor,
             this->getType().getFieldDesc(ShadowColorFieldId),
             const_cast<VRShadowEngineBase *>(this)));

    return returnValue;
}

EditFieldHandlePtr VRShadowEngineBase::editHandleShadowColor    (void)
{
    SFColor4f::EditHandlePtr returnValue(
        new  SFColor4f::EditHandle(
             &_sfShadowColor,
             this->getType().getFieldDesc(ShadowColorFieldId),
             this));


    editSField(ShadowColorFieldMask);

    return returnValue;
}

GetFieldHandlePtr VRShadowEngineBase::getHandleForceTextureUnit (void) const
{
    SFInt32::GetHandlePtr returnValue(
        new  SFInt32::GetHandle(
             &_sfForceTextureUnit,
             this->getType().getFieldDesc(ForceTextureUnitFieldId),
             const_cast<VRShadowEngineBase *>(this)));

    return returnValue;
}

EditFieldHandlePtr VRShadowEngineBase::editHandleForceTextureUnit(void)
{
    SFInt32::EditHandlePtr returnValue(
        new  SFInt32::EditHandle(
             &_sfForceTextureUnit,
             this->getType().getFieldDesc(ForceTextureUnitFieldId),
             this));


    editSField(ForceTextureUnitFieldMask);

    return returnValue;
}


#ifdef OSG_MT_CPTR_ASPECT
void VRShadowEngineBase::execSyncV(      FieldContainer    &oFrom,
                                        ConstFieldMaskArg  whichField,
                                        AspectOffsetStore &oOffsets,
                                        ConstFieldMaskArg  syncMode,
                                  const UInt32             uiSyncInfo)
{
    VRShadowEngine *pThis = static_cast<VRShadowEngine *>(this);

    pThis->execSync(static_cast<VRShadowEngine *>(&oFrom),
                    whichField,
                    oOffsets,
                    syncMode,
                    uiSyncInfo);
}
#endif


#ifdef OSG_MT_CPTR_ASPECT
FieldContainer *VRShadowEngineBase::createAspectCopy(
    const FieldContainer *pRefAspect) const
{
    VRShadowEngine *returnValue;

    newAspectCopy(returnValue,
                  dynamic_cast<const VRShadowEngine *>(pRefAspect),
                  dynamic_cast<const VRShadowEngine *>(this));

    return returnValue;
}
#endif

void VRShadowEngineBase::resolveLinks(void)
{
    Inherited::resolveLinks();


}


OSG_END_NAMESPACE
